//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KruFitNesEntities : DbContext
    {
        public KruFitNesEntities()
            : base("name=KruFitNesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Buy> Table_Buy { get; set; }
        public virtual DbSet<Table_Cost> Table_Cost { get; set; }
        public virtual DbSet<Table_Daily> Table_Daily { get; set; }
        public virtual DbSet<Table_Dispose> Table_Dispose { get; set; }
        public virtual DbSet<Table_EQ> Table_EQ { get; set; }
        public virtual DbSet<Table_ProGrame> Table_ProGrame { get; set; }
        public virtual DbSet<Table_ProMoTion> Table_ProMoTion { get; set; }
        public virtual DbSet<Table_TypePG> Table_TypePG { get; set; }
        public virtual DbSet<Table_User> Table_User { get; set; }
        public virtual DbSet<View_BuyCost> View_BuyCost { get; set; }
        public virtual DbSet<View_EQ> View_EQ { get; set; }
        public virtual DbSet<View_User> View_User { get; set; }
    }
}
