//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_User:toey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_User()
        {
            this.Table_Buy = new HashSet<Table_Buy>();
            this.Table_Daily = new HashSet<Table_Daily>();
        }
    
        public string ID_User { get; set; }
        public string User_Name { get; set; }
        public string User_Pass { get; set; }
        public Nullable<bool> User_Type { get; set; }
        public Nullable<double> User_Height { get; set; }
        public Nullable<double> User_Weight { get; set; }
        public string User_Tell { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Buy> Table_Buy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Daily> Table_Daily { get; set; }
    }
}
