//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_ProMoTion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_ProMoTion()
        {
            this.Table_Buy = new HashSet<Table_Buy>();
        }
    
        public int ID_ProMo { get; set; }
        public string Pro_Name { get; set; }
        public string Pro_Detail { get; set; }
        public Nullable<double> Pro_Price { get; set; }
        public string Pro_Pic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Buy> Table_Buy { get; set; }
    }
}
