//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Cost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Cost()
        {
            this.Table_Buy = new HashSet<Table_Buy>();
            this.Table_Daily = new HashSet<Table_Daily>();
        }
    
        public int ID_Cost { get; set; }
        public string Cost_Name { get; set; }
        public string Cost_Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Buy> Table_Buy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Daily> Table_Daily { get; set; }
    }
}
