//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_TypePG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_TypePG()
        {
            this.Table_ProGrame = new HashSet<Table_ProGrame>();
        }
    
        public int ID_TypePG { get; set; }
        public string TypePG_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_ProGrame> Table_ProGrame { get; set; }
    }
}
