//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Dispose
    {
        public int DIS_ATNO { get; set; }
        public Nullable<int> CE_ATNO { get; set; }
        public Nullable<System.DateTime> DIS_DateOUT { get; set; }
        public Nullable<int> DIS_Status { get; set; }
    
        public virtual Table_EQ Table_EQ { get; set; }
    }
}
