//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Buy:Date
    {
        public int ID_Buy { get; set; }
        public string Buy_User { get; set; }
        public Nullable<int> Buy_Cost { get; set; }
        public Nullable<int> Buy_Pro { get; set; }
        public Nullable<double> TotlePrice { get; set; }
        public Nullable<System.DateTime> Buy_Start { get; set; }
        public Nullable<System.DateTime> Buy_Stop { get; set; }
        public Nullable<bool> Buy_Status { get; set; }
        public string Buy_Pic { get; set; }
    
        public virtual Table_Cost Table_Cost { get; set; }
        public virtual Table_ProMoTion Table_ProMoTion { get; set; }
        public virtual Table_User Table_User { get; set; }
    }
}
