//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_ProGrame
    {
        public int ID_Programe { get; set; }
        public string PG_Name { get; set; }
        public Nullable<int> PG_Type { get; set; }
        public string PG_Detail { get; set; }
        public string PG_Pic { get; set; }
        public string PG_Video { get; set; }
    
        public virtual Table_TypePG Table_TypePG { get; set; }
    }
}
