//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BuyCost
    {
        public string ID_User { get; set; }
        public string Cost_Name { get; set; }
        public string Cost_Price { get; set; }
        public string Pro_Name { get; set; }
        public Nullable<double> Pro_Price { get; set; }
        public Nullable<double> TotlePrice { get; set; }
        public Nullable<System.DateTime> Buy_Start { get; set; }
        public Nullable<System.DateTime> Buy_Stop { get; set; }
    }
}
