//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_User
    {
        public string ID_User { get; set; }
        public string User_Name { get; set; }
        public Nullable<bool> User_Type { get; set; }
        public string User_Tell { get; set; }
        public Nullable<double> User_Weight { get; set; }
        public Nullable<double> User_Height { get; set; }
    }
}
