// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WAB_API.Models
{
    public partial class TableEq
    {
        public TableEq()
        {
            TableDispose = new HashSet<TableDispose>();
            TableSup = new HashSet<TableSup>();
        }

        public int CeAtno { get; set; }
        public string CeNo { get; set; }
        public string CeName { get; set; }
        public string CeNoce { get; set; }
        public int? CePiece { get; set; }
        public double? CePrice { get; set; }
        public double? CePriceTotal { get; set; }
        public int? CeStatus { get; set; }

        public virtual ICollection<TableDispose> TableDispose { get; set; }
        public virtual ICollection<TableSup> TableSup { get; set; }
    }
}