// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WAB_API.Models
{
    public partial class TableTypeUser
    {
        public TableTypeUser()
        {
            TableUser = new HashSet<TableUser>();
        }

        public int IdTypeUser { get; set; }
        public string NameTypeUser { get; set; }

        public virtual ICollection<TableUser> TableUser { get; set; }
    }
}