// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WAB_API.Models
{
    public partial class TableTrainner
    {
        public int IdTrain { get; set; }
        public int? TrainTitle { get; set; }
        public string TrainName { get; set; }
        public string TrainTell { get; set; }
        public string TrainDetail { get; set; }
        public string TrainPic { get; set; }

        public virtual TableTitleName TrainTitleNavigation { get; set; }
    }
}