// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WAB_API.Models
{
    public partial class TableCost
    {
        public TableCost()
        {
            TableBuy = new HashSet<TableBuy>();
        }

        public int IdCost { get; set; }
        public string CostName { get; set; }
        public string CostPrice { get; set; }

        public virtual ICollection<TableBuy> TableBuy { get; set; }
    }
}