// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WAB_API.Models
{
    public partial class TableTypePg
    {
        public TableTypePg()
        {
            TableProGrame = new HashSet<TableProGrame>();
        }

        public int IdTypePg { get; set; }
        public string TypePgName { get; set; }

        public virtual ICollection<TableProGrame> TableProGrame { get; set; }
    }
}