// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WAB_API.Models
{
    public partial class TableProGrame
    {
        public int IdPrograme { get; set; }
        public string PgName { get; set; }
        public int? PgType { get; set; }
        public string PgDetail { get; set; }
        public string PgPic { get; set; }

        public virtual TableTypePg PgTypeNavigation { get; set; }
    }
}