// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WAB_API.Models
{
    public partial class TableProMoTion
    {
        public TableProMoTion()
        {
            TableBuy = new HashSet<TableBuy>();
        }

        public int IdProMo { get; set; }
        public string ProName { get; set; }
        public string ProDetail { get; set; }
        public double? ProPrice { get; set; }

        public virtual ICollection<TableBuy> TableBuy { get; set; }
    }
}