// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WAB_API.Models
{
    public partial class TableSup
    {
        public int CesubAtno { get; set; }
        public string CesubNo { get; set; }
        public string CesubName { get; set; }
        public int? CesubStatus { get; set; }
        public int? CeAtno { get; set; }

        public virtual TableEq CeAtnoNavigation { get; set; }
    }
}