// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WAB_API.Models
{
    public partial class TableBuy
    {
        public int IdBuy { get; set; }
        public int? BuyUser { get; set; }
        public int? BuyCost { get; set; }
        public int? BuyPro { get; set; }
        public double? TotlePrice { get; set; }
        public DateTime? BuyStart { get; set; }
        public DateTime? BuyStop { get; set; }
        public int? ButStatus { get; set; }

        public virtual TableCost BuyCostNavigation { get; set; }
        public virtual TableProMoTion BuyProNavigation { get; set; }
        public virtual TableUser BuyUserNavigation { get; set; }
    }
}