// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WAB_API.Models
{
    public partial class TableUser
    {
        public TableUser()
        {
            TableBuy = new HashSet<TableBuy>();
        }

        public int IdUser { get; set; }
        public string IdCard { get; set; }
        public int? TitleName { get; set; }
        public string UserName { get; set; }
        public string UserId { get; set; }
        public string UserPass { get; set; }
        public int? UserType { get; set; }
        public double? UserHeight { get; set; }
        public double? UserWeight { get; set; }
        public DateTime? UserBirthday { get; set; }
        public string UserTell { get; set; }
        public string UserPic { get; set; }

        public virtual TableTitleName TitleNameNavigation { get; set; }
        public virtual TableTypeUser UserTypeNavigation { get; set; }
        public virtual ICollection<TableBuy> TableBuy { get; set; }
    }
}